openapi: 3.0.3
info:
  title: UniversityToDoList - OpenAPI 3.0
  version: 1.0.2
servers:
  - url: https://universitytodolist.com
tags:
  - name: user
    description: Operations about user
  - name: group
    description: Operations about group
  
paths:
  /user:
    post:
      tags:
        - user
      summary: Create user
      description: 'Create a new user'
      operationId: createUser
      requestBody:
        description: Created user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/xml:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'          
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid data supplied
        '401':
          description: User already exists
    put:
      tags:
        - user
      summary: Update user
      description: Update an existing user
      operationId: updateUser
      parameters:
        - name: name
          in: query
          description: Name of user that needs to be updated
          schema:
            type: string
        - name: surname
          in: query
          description: Surname of user that needs to be updated
          schema:
            type: string
        - name: password
          in: query
          description: Password of user that needs to be updated
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '405':
          description: Validation exception
      security:
        - userPermissions:
          - write
  /user/login:
    get:
      tags:
        - user
      summary: Logs user into the system
      description: ''
      operationId: loginUser
      parameters:
        - name: email
          in: query
          description: The user email
          required: true
          schema:
            type: string
        - name: password
          in: query
          description: The user password
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Login'
            application/xml:
              schema:
                $ref: '#/components/schemas/Login'
        '400':
          description: Invalid email/password supplied
  /user/logout:
    get:
      tags:
        - user
      summary: Log out 
      description: Logs out current logged in user session
      operationId: logoutUser
      responses:
        '200':
          description: successful operation
      security:
        - userPermissions:
          - read
  /user/{userId}:
    get:
      tags:
        - user
      summary: Get user by Id
      description: ''
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          description: 'The ID of user'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getUser'          
            application/xml:
              schema:
                $ref: '#/components/schemas/getUser'
        '400':
          description: Invalid ID supplied
        '404':
          description: User not found
      security:
        - userPermissions:
          - read
    delete:
      tags:
        - user
      summary: Delete user
      description: ''
      operationId: deleteUser
      parameters:
        - name: userId
          in: path
          description: The ID of user which needs to be deleted
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: User not found
      security:
        - userPermissions:
          - admin
  /user/getTasks:
    get:
      tags:
        - user
      summary: Get user tasks
      description: Returns a multiple object of user_task ID
      operationId: getUserTasks
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getTasks'          
      security:
        - userPermissions:
          - read
  /user/getGroups:
    get:
      tags:
        - user
      summary: Get user groups
      description: Returns a multiple object of user_group ID
      operationId: getUserGroups
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getGroups'          
      security:
        - userPermissions:
          - read    
  /group:
    post:
      tags:
        - group
      summary: Create group
      description: Create a new group
      operationId: createGroup
      requestBody:
        description: A new group object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Group'
          application/xml:
            schema:
              $ref: '#/components/schemas/Group'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Group'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Group'
        '405':
          description: Invalid input
      security:
        - userPermissions:
          - read
    put:
      tags:
        - group
      summary: Update group
      description: Update info about group
      operationId: updateGroup
      parameters:
        - name: name
          in: query
          description: 'The new name of group'
          required: true
          schema:
            type: string
        - name: description
          in: query
          description: 'The new description of group'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid data supplied
      security:
        - groupPermissions:
          - update:group
        - userPermissions:
          - read
          - owner
  /group/{groupId}:
    get:
      tags:
        - group
      summary: Find group by ID
      description: Returns a single group
      operationId: getGroupById
      parameters:
        - name: groupId
          in: path
          description: ID of group to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getGroup'          
            application/xml:
              schema:
                $ref: '#/components/schemas/getGroup'
        '400':
          description: Invalid ID supplied
        '404':
          description: Group not found
      security:
        - userPermissions:
          - read
    delete:
      tags:
        - group
      summary: Delete group
      description: Delete everything about group
      operationId: deleteGroup
      parameters:
        - name: groupId
          in: path
          description: ID of the group that needs to be deleted
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: Group not found
      security:
        - groupPermissions:
          - delete:group
        - userPermissions:
          - write
          - owner
          - admin
  /group/addMember:
    post:
      tags:
        - group
      summary: Add member to group
      description: Add a new member to group
      operationId: addMemberToGroup
      parameters:
        - name: memberId
          in: query
          description: ID of the new member
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
        '404':
          description: User not found
        '405':
          description: Invalid input
      security:
        - groupPermissions:
          - add:member
        - userPermissions:
          - write
          - owner
  /group/{groupId}/deleteMember:
    delete:
      tags:
        - group
      summary: Delete member from group
      description: Delete the member from group
      operationId: deleteMemberFromGroup
      parameters:
        - name: memberId
          in: query
          description: ID of the deleting member
          required: true
          schema:
            type: integer
            format: int64
        - name: groupId
          in: path
          description: ID of the group
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
        '404':
          description: User not found
        '405':
          description: Invalid input
      security:
        - groupPermissions:
          - delete:member
        - userPermissions:
          - write
          - owner
  /group/addTask:
    post:
      tags:
        - group
      summary: Add task to group
      description: Add a new task to group
      operationId: addTaskToGroup
      requestBody:
        description: Add a new task
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
          application/xml:
            schema:
              $ref: '#/components/schemas/Task'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Task'
        required: true
      responses:
        '200':
          description: successful operation
        '405':
          description: Invalid input
      security:
        - groupPermissions:
          - add:task
        - userPermissions:
          - write
          - owner
  /group/assignment:
    put:
      tags:
        - group
      summary: Update your status of assignment/task
      description: Update status 
      operationId: updateAssignment
      parameters:
        - name: assignmentId
          in: query
          description: The assignment ID
          required: true
          schema:
            type: integer
            format: int64
        - name: statusId
          in: query
          description: The status ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Assignment/task not found
      security:
        - userPermissions:
          - read
  /group/{groupId}/deleteTask:
    delete:
      tags:
        - group
      summary: Delete task from group
      description: Delete the task from group
      operationId: deleteTaskFromGroup
      parameters:
        - name: taskId
          in: query
          description: ID of the deleting task
          required: true
          schema:
            type: integer
            format: int64
        - name: groupId
          in: path
          description: ID of the group where to delete task
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
        '404':
          description: User not found
        '405':
          description: Invalid input
      security:
        - groupPermissions:
          - delete:task
        - userPermissions:
          - write
          - owner
  /group/{groupId}/getMembers:
    get:
      tags:
        - group
      summary: Get all members of group
      description: Returns a multiple object of members ID
      operationId: getMembersByGroupId
      parameters:
        - name: groupId
          in: path
          description: ID of group to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getMembers'          
        '400':
          description: Invalid ID supplied
        '404':
          description: Group not found
      security:
        - userPermissions:
          - read
          - admin
  /group/{groupId}/getTasks:
    get:
      tags:
        - group
      summary: Get all tasks of group
      description: Returns a multiple object of tasks ID
      operationId: getTasksByGroupId
      parameters:
        - name: groupId
          in: path
          description: ID of group to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getTasks'          
        '400':
          description: Invalid ID supplied
        '404':
          description: Group not found
      security:
        - userPermissions:
          - read
          - admin
components:
  schemas:
    Group:
      required:
        - group_id
        - name
        - owner_id
      type: object
      properties:
        name:
          type: string
          example: 'KN-217 Tasks'
        description:
          type: string
          example: 'This group is created to check KN-217 progress'
      xml:
        name: group
    getGroup:
      required:
        - group_id
        - name
        - owner_id
      type: object
      properties:
        name:
          type: string
          example: 'KN-217 Tasks'
        description:
          type: string
          example: 'This group is created to check KN-217 progress'
        owner_id: 
          type: integer
          format: int64
          example: 22
      xml:
        name: group
    getTasks:
      type: array
      items:
        type: integer
        format: int64
        example: 
          - 1 
          - 2 
          - 4 
          - 6 
    User:
      required:
        - user_id
        - name
        - surname
        - email
        - password
      type: object
      properties:
        name:
          type: string
          example: 'John'
        surname:
          type: string
          example: 'James'
        email:
          type: string
          example: 'john.james.2022@email.com'
        password:
          type: string
          example: 'qwerty2022'
      xml:
        name: user
    getUser:
      required:
        - name
        - surname
        - email
      type: object
      properties:
        name:
          type: string
          example: 'John'
        surname:
          type: string
          example: 'James'
        email:  
          type: string
          example: 'john.james.2022@email.com'
      xml:
        name: user
    Task:
      required: 
        - name
      type: object
      properties:
        name:
          type: string
          example: 'lab 3 PP'
        description:
          type: string
          example: 'deadline by 29.09.2022 (after it half a number of points)'
        groupId:
          type: integer
          format: int64
          example: 22
    getMembers:
      type: array
      items:
        type: integer
        format: int64
        example: 
          - 22 
          - 23 
          - 64 
          - 100 
          - 202
    getGroups:
      type: array
      items:
        type: integer
        format: int64
        example: 
          - 1 
          - 3 
    Login:
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
          example: 'john.james.2022@email.com'
        password:
          type: string
          example: 'qwerty2022'
  securitySchemes:
    groupPermissions:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://universitytodolist.com/oauth/authorize/groupPermissions
          scopes:
            update:group: modify info about group
            delete:group: delete group
            add:member: add new member
            delete:member: delete member from group
            add:task: add task to group
            delete:task: delete task from
    userPermissions:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://universitytodolist.com/oauth/authorize/userPermissions
          scopes:
            read: access to read operations
            write: access to write operations
            owner: access to owner operations
            admin: access to admin operations